baseURL = 'https://directory.council.sleepyhead.app/'
languageCode = 'en-us'
title = 'Game Directory by The Council'
theme = 'tailbliss'
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

enableEmoji = true

[params]
author = "Nusser Studios"
authorimage = "../assets/images/global/author.webp"
og_image = "/images/tailbliss-cover.png"
moto = "Don't take us lightly, or else you will be sorry."
description = "We oversee Sarakahn's game developer society from the dark."
disable_theme_toggle = false
disable_stay_uptodate = true

[params.p1]
heading = "We fight for the right of people, and for the right people."
image = "images/pages/our-mission.png"

[[params.p1.content]]
text = "We do everything in our power, and by any means necessary to ensure the peace of our people."

[[params.p1.content]]
text = "Sollicitudin tristique eros erat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna. Sollicitudin tristique eroserat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna."

[[params.p1.content]]
text = "Rhoncus nisl, libero egestas diam fermentum dui. At quis tincidunt vel ultricies. Vulputate aliquet velit faucibus semper. Pellentesque in venenatis vestibulum consectetur nibh id. In id ut tempus egestas. Enim sit aliquam nec, a. Morbi enim fermentum lacus in. Viverra."

[params.p2]
heading = "We fight everyone we seem threats."
image = "images/pages/hacktoberfest.jpg"

[[params.p2.content]]
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur at purus non enim commodo tincidunt vel in nulla. Aenean pretium dolor non ultricies bibendum. Etiam quis blandit enim. Nunc condimentum ut lorem in faucibus. Phasellus varius ligula et commodo tristique. Nunc sodales nisl nec laoreet vehicula. Donec velit nibh, sollicitudin at nulla a, egestas dignissim eros. Sed lacinia hendrerit interdum. Vestibulum pellentesque sem venenatis nisl tempor accumsan sit amet tempus felis. Mauris leo diam, porttitor nec bibendum id, tempus ac nulla. Etiam congue ornare erat at convallis. Donec in nisi dapibus, mattis risus vel, imperdiet enim. Donec fermentum sit amet tortor nec tincidunt. Nam nec lectus tortor. Nunc sit amet laoreet orci, porta ornare massa. Phasellus eget lorem mi. Nam eleifend ultricies sapien, quis mollis leo bibendum at. Quisque viverra lorem sit amet magna aliquet, et dignissim arcu eleifend."

[params.p3]
heading = "Backed by world-renowned investors"

[[params.p3.content]]
text = "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque. Blandit amet, sed aenean erat arcu morbi. Cursus faucibus nunc nisl netus morbi vel porttitor vitae ut. Amet vitae fames senectus vitae."

[[params.p3.links]]
text = "Meet our investors and advisors"
url = "#"

[[params.p3.logos]]
identifier = "a"
image = "images/global/sample-logo.svg"
alt = "a"

[[params.p3.logos]]
identifier = "b"

[[params.p3.logos]]
identifier = "c"

[[params.p3.logos]]
identifier = "d"

[[params.p3.logos]]
identifier = "e"

[[params.p3.logos]]
identifier = "f"

[params.p4]
heading = "From the blog"

[[params.p4.content]]
text = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa libero labore natus atque, ducimus sed."

[params.p5]
heading = "Stay Up to Date"
action = "#"
label = "Email address"
placeholder = "Enter your email"
button = "Notify me"

[[params.p5.content]]
text = "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque."

[params.social_media.github]
enabled = false
url = "https://github.com/nusserstudios"

[params.social_media.facebook]
enabled = true
url = "https://www.facebook.com/devgat"

[params.social_media.instagram]
enabled = false

[params.social_media.twitter]
enabled = false


[menu]

# [[menu.main]]
# name = "Home"
# identifier = "menu.home"
# url = "/"
# weight = 1

# [[menu.main]]
# name = "About Us"
# weight = 3
# identifier = "about"
# pre = "dropdown"

[[menu.main]]
name = "Games"
weight = 1
identifier = "games"
url = "/games"

[[menu.main]]
name = "Browse by Publishers"
weight = 2
identifier = "publishers"
url = "/publishers"

[[menu.main]]
name = "Browse by Developers"
weight = 3
identifier = "developers"
url = "/developers"

[[menu.footer]]
name = "Home"
identifier = "menu.home"
url = "/"
weight = 1

# [[menu.footer]]
# name = "Contact"
# weight = 10
# url = "/contact"

[markup]
defaultMarkdownHandler = 'goldmark'

[taxonomies]
    developer = 'developers'
    publisher = 'publishers'